CREATE TABLE IF NOT EXISTS account_table (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    balance REAL,
    type TEXT NOT NULL,
    currency TEXT NOT NULL,
    lastUpdated DATETIME DEFAULT CURRENT_TIMESTAMP  
);