import { AccountType } from '../types';

export interface AccountData {
    id?: string; // generated by database
    name: string;
    balance: number;
    type: AccountType;
    currency: string;
    lastUpdated?: Date; // generated by database
}