import {AccountType, Currency} from '../types/index.js';

export interface AccountData {
  id: number; // generated by database
  name: string;
  balance: number;
  type: AccountType;
  currency: Currency;
  lastUpdated: Date; // generated by database
}

export type InsertAccountData = Omit<AccountData, 'id' | 'lastUpdated'>;

export type UpdateAccountData = Partial<InsertAccountData>;
