import { AccountType, Currency } from '../types/index.js';

export interface AccountData {
    id: number; // generated by database
    name: string;
    balance: number;
    type: AccountType;
    currency: Currency;
    lastUpdated: Date; // generated by database
}

// used to create accounts
// leaves out id and lastUpdated
export type InsertAccountData = Omit<AccountData, 'id' | 'lastUpdated'>

// used to update accounts
// every attribute is optional
export type UpdateAccountData = Partial<InsertAccountData>