export interface CategoryData {
    id: string; // generated by database
    name: string;
    lastUpdated?: Date; // generated by database
    budget: number | null;
}

export type InsertCategoryData = Omit<CategoryData, 'id' | 'lastUpdated'>

export type UpdateCategoryData = Partial<InsertCategoryData>