export interface CategoryData {
    id: number; // generated by database
    name: string;
    lastUpdated: Date; // generated by database
    budget: number | null;
}

export type InsertCategoryData = Omit<CategoryData, 'id' | 'lastUpdated'>

export type UpdateCategoryData = Partial<InsertCategoryData>