import { TransactionType } from '../types/index.js';

export interface TransactionData {
    id: number; // generated by database
    amount: number;
    date: Date; // when it was booked
    categoryId: number; // e.g. health, food, transport
    accountId: number;
    type: TransactionType; // e.g. ausgabe / einnahme
    lastUpdated: Date; // generated by database

    description?: string | null;
}

export type InsertTransactionData = Omit<TransactionData, 'id' | 'lastUpdated'>

export type UpdateTransactionData = Partial<InsertTransactionData>
