import { TransactionType } from '../types/index.js';

export interface TransactionData {
  id: number; // generated by database
  amount: number;
  date: Date;
  categoryId: number;
  accountId: number;
  type: TransactionType;
  lastUpdated: Date; // generated by database

  description?: string | null;
}

export type InsertTransactionData = Omit<TransactionData, 'id' | 'lastUpdated'>;

export type UpdateTransactionData = Partial<InsertTransactionData>;
