import { TransactionType } from '../types';

export interface TransactionData {
    id?: string; // generated by database
    amount: number;
    date: Date; // when it was booked
    categoryId: string; // e.g. health, food, transport
    accountId: string;
    type: TransactionType; // e.g. ausgabe / einnahme
    lastUpdated?: Date; // generated by database

    description?: string | null;
}